- hosts: node
  become: true
  tasks:
    - name: Create namespace for webapp
      shell:  sudo kubectl create namespace webapp-namespace || true
    - name: Create new webapp deployment
      shell: sudo kubectl apply -f /home/azureuser/deployment.yml
    - name: Create new webapp service
      shell: sudo kubectl apply -f /home/azureuser/service.yml